### ISSUE TITLE
Visual Attribute Transfer through Deep Image Analogy

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#23]
元論文：
https://arxiv.org/pdf/1705.01088.pdf

参考ページ（日本語）
https://github.com/arXivTimes/arXivTimes/issues/301

Github code
https://github.com/msracver/Deep-Image-Analogy

**Comment by Hirokazu-Narui** [comment]
以下のAとB'の画像を与えるだけで、A'とBの画像を出力するDeep Image Analogy.
（色、テクスチャ、スタイルなどの変換に関する）
論文中はA:A' = B:B'と表現し、AとA'およびBとB'は配置が一緒だが、属性が異なる。

![fig1](https://cloud.githubusercontent.com/assets/19613247/25827404/e5568f90-33ff-11e7-82c8-29e719c8c3e6.jpg)


1. 学習済みのVGG19のネットワークを使って、AとB'の特徴マップピラミッドを得る。
（特徴マップはVGG19の各レイヤーのReLUの後の出力。）

![fig4](https://cloud.githubusercontent.com/assets/19613247/25827477/41d1ab56-3400-11e7-9acf-7aa682fd3e7c.jpg)


2. AとBはパーツがマッピングされている場所が異なるので、写像するマッピングファンクションを以下の式より計算する。（p, qはパーツの領域？x, yはそのパーツを構成するピクセル？よくわからない・・・）

![eq2](https://cloud.githubusercontent.com/assets/19613247/25827683/522842a2-3401-11e7-958c-95f1c71c83f8.jpg)

3. 2層目以降は以下の図のように重み付けした和を使って特徴マップを計算していく。

![fig6](https://cloud.githubusercontent.com/assets/19613247/25828050/ff760574-3402-11e7-9426-bfcb32b53dc1.jpg)


結果が凄い。。。
![fig14](https://cloud.githubusercontent.com/assets/19613247/25828254/1992c7b6-3404-11e7-8d00-fc4b98abd45a.jpg)

![fig15](https://cloud.githubusercontent.com/assets/19613247/25828257/1d5cce64-3404-11e7-8f3d-40178c1a502a.jpg)

**Comment by msrks** [comment]
>理解が追いつかず、気になってpaper読み始めてしまいました。以下メモ

A : A' = B : B' の関係の画像を得る（AとA'は 意味的に似てて、AとBは外観的に似るように）

具体的には、(A, B')から(A', B)を得る

### 1. Preprocess: 全ての層のF(A)とF(B')を得る

AとB'をVGG19に通して feature mapをF(A)とF(B')得る

**Comment by msrks** [comment]
### 2. Initialize Deep Feature Map: 最上位層のF(A')とF(B)を得る

最上位のFeature Mapを以下で初期化する。

= 意味的に似てるなら、最上位のFeature Mapは同じであるべきという考え方

```
F(A') = F(A)、F(B)=F(B')
```

**Comment by msrks** [comment]
### 3. Get Mapping Function by NNF search

* A to B の Forward Mapping Function
* B to A の Reverse Mapping Function　を求める。

=>ある pixel周りの 3x3の patchを考えて、mapping後のL2距離が一番小さかった部分(=argmin)を mapping先と定める。

= Mapping Functionは外観を保っていたいので pixelレベルで似てほしい

`Nearest Neighbor Field search` (式2) により mapping functionを求める

<img width="400" alt="2017-05-11 0 16 35" src="https://cloud.githubusercontent.com/assets/9496670/25906701/531fa8a4-35e0-11e7-8f1b-893dc778c6f6.png">

**Comment by msrks** [comment]
### 4. 最上位層以外のF(A')とF(B)を得る

F(A')を得ることを考える。F(B)は同じようなことなので省略。

基本的な考え方としては、F(A')を得るためには、以下の式のイメージ

<img width="300" alt="2017-05-11 1 07 57" src="https://cloud.githubusercontent.com/assets/9496670/25908869/4ec34f62-35e6-11e7-96c2-0a38a4e61b0b.png">

* Aと意味的に近くあってほしいので、neuronがよく興奮しているところ（重みW）のF(A)とは似ていたい
* B'とも外観的に近くあってほしいので、`#3`で求めた mapping functionを使ってB'のA'へのmappingに対してF(・)を計算して、それ(=R)と似ていてほしい

ただし L-1層目のmapping functionはまだ計算できてないので、この方法は使えない（L層のmapping functionしかこの段階ではわからない）。なのでRを計算するために、上の2つ目の考え方を下の図の操作で代替する。

<img width="400" alt="2017-05-11 1 04 18" src="https://cloud.githubusercontent.com/assets/9496670/25909254/91bdee48-35e7-11e7-92fe-534f6d623084.png">

1. B'をWarpする。・・・

つづきはまた今度・・・つかれた・・・

**Comment by msrks** [comment]
この論文難しいです・・・・

**Comment by msrks** [comment]
正直、cycleGANで同じことできんじゃね？　って思うんですけどどう思いますか？？

**Comment by msrks** [comment]
下のアルゴリズムでやってることは大体、上のメモで満足したので、あとは誰かの解説を待ちたい <- 人任せ

<img width="350" alt="2017-05-11 1 28 15" src="https://cloud.githubusercontent.com/assets/9496670/25909766/256444f2-35e9-11e7-9c5e-5bc5c3a0ee0a.png">

**Comment by msrks** [comment]
Fig 15みた感じ、neural styleより contentsがちゃんと保存されてる感あるけど、
neural styleとの比較についてはコメントあるんだろうか。その辺気になる
