### ISSUE TITLE
Matrix Factorization

### ISSUE THREAD

**Issue by msrks** [furukawa-ai/deeplearning_papers#29]
時間のあるときに勉強しといたほうがいいと思われる

**Comment by msrks** [comment]
モデル圧縮手法の概要をざっと掴むのにとてもよかった

https://nico-opendata.jp/ja/casestudy/model_compression/index.html

* matrix factorization
* tensor factorization
* weight sharing
* distillation
* serialization of sparse matrix
* 量子化

について解説あり。どれも読めばすぐわかる

**Comment by msrks** [comment]
#30 とも関連ありですね

**Comment by Hirokazu-Narui** [comment]
Distillationについて（日本語）
http://qiita.com/HirofumiYashima/items/fc220b66d16b2d2078c4
