### ISSUE TITLE
Kullback-Leibler Divergence

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#31]
分布の距離を測る指標のKL距離についての記事。
https://www.countbayesie.com/blog/2017/5/9/kullback-leibler-divergence-explained

**Comment by msrks** [comment]
個人的にはPRMLの解説がわかりやすかったですね。

**Comment by msrks** [comment]
タカハシ春の GAN 祭り！〜 一日一GAN(๑•̀ㅂ•́)و✧ 〜
http://tech-blog.abeja.asia/entry/everyday_gan

結構良い
