### ISSUE TITLE
One-Shot Imitation Learning

### ISSUE THREAD

**Issue by msrks** [furukawa-ai/deeplearning_papers#32]
https://blog.openai.com/robots-that-learn/

Now, we’ve developed and deployed a new algorithm, one-shot imitation learning, allowing a human to communicate how to do a new task by performing it in VR. Given a single demonstration, the robot is able to solve the same task from an arbitrary starting configuration.

**Comment by msrks** [comment]
https://arxiv.org/abs/1703.07326

Imitation learning has been commonly applied to solve different tasks in isolation. This usually requires either careful feature engineering, or a significant number of samples. This is far from what we desire: ideally, robots should be able to learn from very few demonstrations of any given task, and instantly generalize to new situations of the same task, without requiring task-specific engineering. In this paper, we propose a meta- learning framework for achieving such capabil- ity, which we call one-shot imitation learning.

Our ex- periments show that the use of soft attention al- lows the model to generalize to conditions and tasks unseen in the training data. We anticipate that by training this model on a much greater variety of tasks and settings, we will obtain a general system that can turn any demonstrations into robust policies that can accomplish an over- whelming variety of tasks.

**Comment by Hirokazu-Narui** [comment]
Blogの一番上の動画がすごくわかりやすい！
https://player.vimeo.com/video/217578517

Vision NetworkとImitation Networkで構成。
One shot Imitation Learning時間あるときに読みたいですー。

**Comment by msrks** [comment]
imitation networkの学習方法がよくわからないです
