### ISSUE TITLE
Google Drawing dataset

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#37]
https://quickdraw.withgoogle.com/data
手書きの絵のデータセットがGoogleから公開されています。
Google cloud platform上でダウンロード可能。

https://console.cloud.google.com/storage/browser/quickdraw_dataset/

あとA.I. Experimentというのも公開されています。
https://aiexperiments.withgoogle.com/

Open AIのDistillみたいなものっぽい。

**Comment by msrks** [comment]
A.I. Experimentいいっすね！

**Comment by msrks** [comment]
単純に検索して手に入る画像・動画以外の、
ラベルなしデータ（今回だとストロークのjsonデータ）
が今後増えて行くのかもしれませんね（生成モデル向けに）
