### ISSUE TITLE
MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications

### ISSUE THREAD

**Issue by msrks** [furukawa-ai/deeplearning_papers#4]
https://arxiv.org/abs/1704.04861

**Comment by ichikawa-y** [comment]
Google MobileNet implementation with Keras 
https://github.com/rcmalli/keras-mobilenet


MobileNet build with Tensorflow 
https://github.com/Zehaos/MobileNet

Kerasの作者@fcholletさんのCVPR'17論文XceptionとGoogleのMobileNets論文を読んだ
http://qiita.com/yu4u/items/34cd33b944d8bdca142d
