### ISSUE TITLE
Attention Is All You Need

### ISSUE THREAD

**Issue by msrks** [furukawa-ai/deeplearning_papers#44]
https://arxiv.org/abs/1706.03762

The dominant sequence transduction models are based on complex recurrent or convolutional neural networks in an encoder-decoder configuration. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English-to-German translation task, improving over the existing best results, including ensembles by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.0 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data.

**Comment by msrks** [comment]
RNN、CNN使わずにSOTA。使ったのはAttentionだけ！衝撃すぎる

**Comment by msrks** [comment]
<img width="300" alt="2017-06-22 16 11 50" src="https://user-images.githubusercontent.com/9496670/27421504-a732faee-5765-11e7-85de-90d5bc17325f.png">


<img width="400" alt="2017-06-22 16 11 59" src="https://user-images.githubusercontent.com/9496670/27421493-9d7f4d90-5765-11e7-9071-d37bf20c8b17.png">

**Comment by msrks** [comment]
slicenetを超えてSOTA
https://research.googleblog.com

**Comment by ichikawa-y** [comment]
おー、すごいですね
 assignありがとうございます、次はこの論文を紹介しますかね。
Attention Is All You Need。attension恐るべしですね。

**Comment by ichikawa-y** [comment]
・松尾研の勉強会資料(Slideshare)
https://www.slideshare.net/DeepLearningJP2016/dlattention-is-all-you-need
・著者の解説(Slideshare)
https://www.slideshare.net/ilblackdragon/attention-is-all-you-need
