### ISSUE TITLE
One Model To Learn Them All

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#57]
(arXiv)　https://arxiv.org/abs/1706.05137

#45 Depthwise Separable Convolutions for Neural Machine Translationと関連あり。

音声→文章(Wall Street Journal)
文章→品詞(Wall Street Journal)
画像→ラベル(ImageNet dataset)
画像→文章（COCO dataset）
文章→文章（言語翻訳）
のタスクを一つのディープラーニングモデルで学習する。

それぞれのタスクでState of the artまでは到達しないが、
単独のタスクを学習した結果よりも、他のタスクも同時に学習したほうが結果がよくなる。

**Comment by msrks** [comment]
気になってたやつなのですごいうれしいです！
