### ISSUE TITLE
Siamese Neural Networks for One-shot Image Recognition

### ISSUE THREAD

**Issue by msrks** [furukawa-ai/deeplearning_papers#58]
http://www.cs.cmu.edu/~rsalakhu/papers/oneshot1.pdf

**Comment by msrks** [comment]
このブログがとてもいい　https://sorenbouma.github.io/blog/oneshot/

**Comment by ichikawa-y** [comment]
https://www.slideshare.net/DeepLearningJP2016/dlattention-is-all-you-need
松尾研の輪読会のslidshare.
