### ISSUE TITLE
Matching Networks for One Shot Learning

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#6]
https://arxiv.org/abs/1606.04080

**Comment by msrks** [comment]
参考: http://rylanschaeffer.github.io/content/research/one_shot_learning_with_memory_augmented_nn/main.html

**Comment by msrks** [comment]
karpathyによるメモ:
https://github.com/karpathy/paper-notes/blob/master/matching_networks.md

**Comment by msrks** [comment]
<img width="673" alt="2017-05-07 21 59 19" src="https://cloud.githubusercontent.com/assets/9496670/25781181/03d0f6d4-3371-11e7-9571-b9d0c36f1ee7.png">

**Comment by msrks** [comment]
1. (x_i, y_i) のペアを元に、key = y_i に対する 特徴ベクトル g(x_i)のデータベースをexternal memory上に学習する
2. 入力 x^に対する 特徴ベクトル f(x)と 各 g(x_i)の類似度を計算し、Soft Attentionを使って y_iを決定する

Matching Networks は特徴ベクトルへの埋め込み関数、g(・)、f(・)を学習する

<img width="612" alt="2017-05-07 21 59 27" src="https://cloud.githubusercontent.com/assets/9496670/25781186/120d30be-3371-11e7-86a9-ab25ecda83ea.png">
