### ISSUE TITLE
AnoGAN (Unsupervised Anomaly Detection with Generative Adversarial Networks to Guide Marker Discovery)

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#69]
arXiv : https://arxiv.org/abs/1703.05921

### やりたい事：正常データだけを使って、教師なしでネットワークを学習し、異常データが入力された時には異常の箇所を特定したい。
![anogan_fig1](https://user-images.githubusercontent.com/19613247/29279280-31d96edc-80cc-11e7-889c-3664af033a05.jpg)

### 手法：正常データだけを使って学習したGeneratorに対して、画像xに最も近いG(z)を生成するzを求めたい。
→以下に定義したロスを使ってzを更新。

![anogan_eq5](https://user-images.githubusercontent.com/19613247/29279715-9742eb26-80cd-11e7-8653-f863c1c2b6ce.jpg)

L_Rは、入力画像xと生成画像R(z)のResidual Loss。正常画像であればこれは0に収束。
![anogan_eq3](https://user-images.githubusercontent.com/19613247/29279722-9e11880e-80cd-11e7-9233-80fc095cb2df.jpg)

L_Dは、Discriminator Loss。GANのDiscriminatorが抽出する特徴。正常画像であればマッチングするはず。
![anogan_eq4](https://user-images.githubusercontent.com/19613247/29279728-a2b0e22e-80cd-11e7-8336-cb16f599a2c7.jpg)

上記のLossを使ってIterし、最終的なzを使って、異常スコアを計算。
![anogan_eq6](https://user-images.githubusercontent.com/19613247/29279986-6a160074-80ce-11e7-82d6-ae3ceff26cdc.jpg)

### 結果：一行目は入力画像。二行目は生成された画像。
正常画像で学習したマニフォールドからのzでは、異常箇所は生成できないため、差分から異常データの場所が特定できる。
![anogan_fig3](https://user-images.githubusercontent.com/19613247/29280051-a4172eec-80ce-11e7-846c-21e820c26f3c.jpg)

**Comment by msrks** [comment]
同じネタ書いてしまいました（#70）成井さんのやつの方が詳しいですね！ありがとうございます

**Comment by saiful9379** [comment]
Above of this equation explain please
