### ISSUE TITLE
Applying deep learning to distinguish drivers from passengers using sensor data

### ISSUE THREAD

**Issue by Hirokazu-Narui** [furukawa-ai/deeplearning_papers#77]
スマホの加速度センサから、運転中の特徴を抽出し、ドライバーのIDを識別&運転手なのか乗客なのかを識別する。加速度センサから特徴を抽出するネットワーク構造は参考になるかも。

http://www.sentiance.com/2017/09/25/deep-learning-on-passenger-and-driver-behavior-analysis-using-sensor-data/

近い論文
http://papers.www2017.com.au.s3-website-ap-southeast-2.amazonaws.com/proceedings/p351.pdf

**Comment by msrks** [comment]
1-d conv で特徴したのを LSTM layerに入れて、時間方向の情報を統合した後、denseを通して分類

* window-size = 30sec
* num_windows = 10

![d-p-sentiance-04](https://user-images.githubusercontent.com/9496670/30838078-60247314-a2a4-11e7-81c3-17e094ebafbd.png)
