### ISSUE TITLE
Complex-YOLO: Real-time 3D Object Detection on Point Clouds

### ISSUE THREAD

**Issue by msrks** [furukawa-ai/deeplearning_papers#98]
- input: Velodyne64-Lidar Point Cloud
- output: 3D bounding box

50fps on a NVIDIA TitanX GPU で SOTA。すごい。

https://arxiv.org/abs/1803.06199

Lidar based 3D object detection is inevitable for autonomous driving, because it directly links to environmental understanding and therefore builds the base for prediction and motion planning. The capacity of inferencing highly sparse 3D data in real-time is an ill-posed problem for lots of other application areas besides automated vehicles, e.g. augmented reality, personal robotics or industrial automation. We introduce Complex-YOLO, a state of the art real-time 3D object detection network on point clouds only. In this work, we describe a network that expands YOLOv2, a fast 2D standard object detector for RGB images, by a specific complex regression strategy to estimate multi-class 3D boxes in Cartesian space. Thus, we propose a specific Euler-Region-Proposal Network (E-RPN) to estimate the pose of the object by adding an imaginary and a real fraction to the regression network. This ends up in a closed complex space and avoids singularities, which occur by single angle estimations. The E-RPN supports to generalize well during training. Our experiments on the KITTI benchmark suite show that we outperform current leading methods for 3D object detection specifically in terms of efficiency. We achieve state of the art results for cars, pedestrians and cyclists by being more than five times faster than the fastest competitor. Further, our model is capable of estimating all eight KITTI-classes, including Vans, Trucks or sitting pedestrians simultaneously with high accuracy.

<img width="651" alt="2018-03-20 1 17 47" src="https://user-images.githubusercontent.com/9496670/37608163-33e7e8d6-2bdd-11e8-8b87-cd17481e55a7.png">

<img width="653" alt="2018-03-20 1 21 32" src="https://user-images.githubusercontent.com/9496670/37608166-3639f20a-2bdd-11e8-968f-dcad8d5adf63.png">

<img width="660" alt="2018-03-20 1 21 44" src="https://user-images.githubusercontent.com/9496670/37608178-3a357f6e-2bdd-11e8-8fa6-907a347efd43.png">

<img width="662" alt="2018-03-20 1 21 59" src="https://user-images.githubusercontent.com/9496670/37608184-3d88957a-2bdd-11e8-912f-066853e04ad9.png">

<img width="666" alt="2018-03-20 1 22 19" src="https://user-images.githubusercontent.com/9496670/37608190-40f22758-2bdd-11e8-842b-d5d0f705eaa6.png">

**Comment by pulkitgoyal1506** [comment]
Is code available online? I am trying to implement this.

**Comment by lucasjinreal** [comment]
@pulkitgoyal1506 How's implementation goes?

**Comment by ghimiredhikura** [comment]
hi @pulkitgoyal1506, 

check this one: [https://github.com/ghimiredhikura/Complex-YOLO](https://github.com/ghimiredhikura/Complex-YOLO)
